apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: KAIA
        image: your-app-image:tag
        env: 
        - name: MONGODB_URI
          value: mongodb+srv://Sol:SEvoQqDSdmZwhpx3@cluster0.nrfdmbx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"